import React,{Component} from 'react';

class Dalat extends Component{
    render(){
        return(
           
              
                    <div className="row">
                      <div className="col-sm-8">
                        <h1 className="tt-detail">TOP 10 ĐỊA ĐIỂM DU LỊCH ĐẸP VÀ HẤP DẪN NHẤT TẠI ĐÀ LẠT</h1>
                        <div className="time-dt"><i className="fa fa-clock-o" aria-hidden="true" /> 05.07.2018</div>
                        <div className="content-dt">
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Địa điểm du lịch đẹp tại Đà Lạt – Thành phố Đà Lạt vốn có nhiều cảnh đẹp, nổi tiếng với nền khí hậu ôn hòa, mát mẻ quanh năm, là điểm du lịch tuyệt vời mà mọi du khách đều muốn đến để tham quan và trải nghiệm. Đến Đà Lạt mộng mơ, bạn sẽ được chiêm ngưỡng những điểm tham quan thú vị đã đến rồi thì đều bị vẻ đẹp của cảnh sắc nơi đây níu chân không muốn rời xa. Sau đây, Top 10 Việt Nam chia sẻ đến bạn những địa điểm du lịch đẹp va hấp dẫn nhất tại Đà Lạt giúp bạn có thêm nhiều thông tin bổ ích, và lựa chọn được những điểm dừng chân phù hợp nhất.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>1. NÚI LANGBIANG</span></span></strong></p>
                          <p style={{textAlign: 'center'}}><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/langbiang-1.png" style={{width: '640px', height: '426px'}} /></span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Núi Langbiang thuộc địa phận huyện Lạc Dương. Đây là ngọn núi cao nhất Đà Lạt. Nơi đây thu hút rất nhiều du khách trong và ngoài nước đến dã ngoại cũng như thám hiểm và chinh phục độ cao. Có nhiều cách để chinh phục các đỉnh núi trong dãy Langbiang như đi xe Jeep, đi bộ theo đường nhựa. Nơi này có 2 ngọn núi được người dân đặt tên là Núi Ông và Núi Bà. Khi đến đây, du khách được ngắm nhìn khung cảnh hùng vĩ của cao nguyên Langbiang. Vẻ đẹp lãng mạn trong sương mù của cả thành phố, tham gia những hoạt động thể thao độc đáo như leo núi bằng dây, nhảy dù lượn.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>2. THUNG LŨNG TÌNH YÊU</span></span></strong></p>
                          <p style={{textAlign: 'justify'}}><span style={{fontFamily: 'arial, helvetica, sans-serif', fontSize: '14px'}}>Nằm cách trung tâm thành phố Đà Lạt khoảng 5km về phía Bắc. Thung lũng Tình Yêu không chỉ là điểm đến lãng mạn cho những cặp đôi khi đi du lịch. Nơi đây còn hấp dẫn mọi du khách bởi cảnh sắc đẹp mê hồn, núi non hữu tình. Đó là nơi đập Đa Thiện đã quy tụ những dòng suối nhỏ chảy từ đồi núi cao thành hồ Đa Thiện trong vắt uốn mình quanh thung lũng rợp bóng thông xanh.</span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontFamily: 'arial, helvetica, sans-serif', fontSize: '14px'}}><img alt="" src="/uploads/images/diem-tham-quan/thunglung-tinhyeu-1.jpg" style={{width: '640px', height: '360px'}} /></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Những con đường đất đỏ uốn lượn vòng vèo có thể đưa khách lên đồi hoặc dẫn đền tận đỉnh núi Langbian thấp thoáng trong mây. Khu du lịch giờ đây đã trở nên hấp dẫn hơn bao giờ hết. Là một trong những địa điểm tham quan, dã ngoại, vui chơi giải trí không thể thiếu trong chương trình tour của Quý khách và du khách từ mọi miền đất nước đến với thành phố Đà Lạt mộng mơ.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>3. ĐỒI MỘNG MƠ</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Một trong những địa điểm du lịch nổi tiếng nhất ở Đà Lạt chính là đồi Mộng Mơ. Nơi đây có thắng cảnh thơ mộng và xanh mát. Tạo nên một bức tranh đẹp hiền dịu góp phần làm nên điểm nhấn của du lịch Đà Lạt mà bất cứ ai khi đến đây cũng nao lòng, ngẩn ngơ.</span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Cách trung tâm thành phố Đà Lạt 4km theo hướng Bắc. Đồi Mộng Mơ – một điểm đến lý tưởng mà du khách khi đến Đà Lạt chắc chẳng bao giờ bỏ qua. Từ người già đến người trẻ, hay những cặp đôi đang yêu nhau cho đến những cặp đôi mới cưới,…Đều ghé thăm, theo con đường dẫn lối đến đây.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/doi-mong-mo-1.jpg" style={{width: '500px', height: '293px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Đồi Mộng Mơ mang đến cho bất kỳ ai nghe thấy cũng thấy dịu dàng. Là cái hồn của Đà Lạt thu nhỏ với những kiệt tác nghệ thuật từ thiên nhiên. Và con người cho du khách khi đến đây đều cảm thấy bình yên, nhẹ nhàng.</span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Có lẽ đây là nơi để du khách có thể hòa mình, thả hồn vào thiên nhiên trong xanh, để khám phá những nét đẹp về cảnh sắc, con người nơi đây, bình dị, mộc mạc và chân thành.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>4. CHỢ ĐÀ LẠT</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Chợ Đà Lạt là trung tâm thương mại lớn nhất của thành phố sương mù các hoạt động mua bán, giao thương diễn ra tấp nập từ sáng sớm cho tới đêm muộn. Ngoài cung cấp các mặt hàng thiết yếu cho người dân nơi đây còn cung cấp các nông sản. Đặc sản quý hiếm của vùng đất này tới du khách khi có dịp tới với Đà Lạt.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/cho-dalat.jpg" style={{width: '640px', height: '425px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Đà Lạt được thiên nhiên ban tặng cho khí hậu ôn hòa cho nên trồng được nhiều loại rau như bắp cải, súp lơ, bông atisô, tầng ô, bó xôi…. Những loại rau sạch này vẫn được đem đến các tỉnh lân cận và xuất khẩu ra nước ngoài. Chợ Đà Lạt với những nét đặc trưng riêng của phố núi có sự cuốn hút đến lạ kì. Ghé đến đây, du khách không chỉ có cơ hội mua sắm những đặc sản Đà Lạt mà còn được chiêm ngưỡng, tìm hiểu về công trình kiến trúc đặc sắc bậc nhất thành phố này.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>5. THIỀN VIỆN TRÚC LÂM</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Đến với Đà Lạt, du khách không thể bỏ qua vẻ đẹp thanh tịnh của Thiền viện Trúc Lâm Đà Lạt với kiến trúc độc đáo và cảnh thiên nhiên tươi đẹp. Thiền viện Trúc Lâm Đà Lạt nằm cách trung tâm thành phố 5 km. Nên rất thuận tiện cho du khách đến tham quan cảnh đẹp và tận hưởng không khí thanh bình nơi đây. Tọa lạc ở vị trí rất đẹp, ngay trên núi Phượng Hoàng với hồ Tuyền Lâm nằm ngay bên cạnh. Tất cả tạo nên một bức tranh phong cảnh nơi thiền viện vô cùng lãng mạn và thanh bình.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/thien-vien-truc-lam-1.jpg" style={{width: '640px', height: '340px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Thiền viện Trúc Lâm ở Đà Lạt vừa có quang cảnh thiên nhiên tươi đẹp như một điểm du lịch hấp dẫn vừa mang không khí thanh tịnh của thế giới tâm linh. Trong nhịp sống hiện đại, quay cuồng với những giá trị vật chất phù phiếm thì chính những phút giây tĩnh tâm tại Thiền viện Trúc Lâm Đà Lạt sẽ giúp tâm hồn của bạn được yên ổn, để bình tâm tìm được hướng đi cho cuộc đời.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>6. CHÙA LINH PHƯỚC</span></span></strong></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/chua-linh-phuoc-1.jpg" style={{width: '640px', height: '306px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Chùa Linh Phước – ngôi chùa độc đáo bậc nhất Đà Lạt hấp dẫn nhiều du khách bởi vẻ đẹp cầu kỳ mà đơn giản. Chùa Linh Phước tọa lạc tại số 120 Tự Phước. Thuộc địa bàn Trại Mát, cách trung tâm thành phố Đà Lạt 8km, trên quốc lộ 20. Vẻ đẹp có một không hai của ngôi chùa Linh Phước là phong cách kiến trúc độc đáo, lạ mắt, được trang trí toàn bằng mẻ chén, ve chai. Chùa có tòa linh tháp 7 tầng, cao 37m được cho là tòa tháp cao nhất trong số các ngôi chùa ở Đà Lạt. Tòa tháp này nằm phía trước Long Hoa Viên, nơi đặt các bức tượng Phật lớn.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>7. THÁC DATANLA</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Đà Lạt nổi tiếng với nhiều thác nước đẹp và hùng vĩ như Thác Voi, thác Bobla,…Trong đó không thể không kể đến vẻ đẹp quyến ruc của thác Dantala Đà Lạt. Một trong những thác nước thu hút nhiều khác du khách du lịch ghé thăm.</span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Nằm bên đèo Prenn cách Đà Lạt chừng 7km. Thác Datanla được xem là một trong những điểm du lịch hấp dẫn của du khách khi đến thành phố hoa. Vì vẻ hoang sơ quyến rũ của thiên nhiên và cảnh sắc nơi đây.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/thac-datanla-1.jpg" style={{width: '640px', height: '406px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Thác Datanla có lượng nước dồi dào do thượng nguồn là nguồn nước ổn định. Không ồn ào do chảy qua nhiều thềm đá. Thác đổ từ ghềnh cao 20m, nước suối phần dưới tạo thành khu vực nước rất trong nên gọi là Suối Tiên. Phần sâu hun hút phía trên có một vực sâu gọi là Vực Tử Thần. Nhờ có ngọn thác này nên một cánh quân đã trụ lại và bảo toàn được lực lượng.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>8. QUẢNG TRƯỜNG LÂM VIÊN ĐÀ LẠT</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Quảng trường Lâm Viên tọa lạc giữa “trái tim” của thành phố hoa. Hướng ra Hồ Xuân Hương với tổng diện tích lên đến 72.000 m2. Không chỉ mang đến không gian rộng lớn, thoáng mát. Với nhiều hoạt động giải trí mà Quảng trường Lâm Viên. Còn ấn tượng với công trình nghệ thuật khổng lồ với khối bông hoa dã quỳ và khối nụ hoa được thiết kế bằng kính màu lạ mắt.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/quang-truong-lam-vien-1.jpg" style={{width: '507px', height: '333px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Đóa hoa dã quỳ cao hơn 18m, diện tích 1.200 m2. Bên trong là cùng biểu diễn nghệ thuật với 1.500 chỗ ngồi. Theo thiết kế cánh hoa màu vàng sẽ ôm sát theo mái cong trong. Nhụy hoa thiết kế nghiêng để mọi người nhìn vào dễ dàng liên tưởng đến hoa dã quỳ.</span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Quảng trường Lâm Viên là điểm dừng chân không thể bỏ qua trong chuyến du lịch Đà Lạt của mọi du khách. Hãy đến Đà Lạt ngày để được ngắm nhìn vẻ đẹp ngoài đời thực của quảng trường Lâm Viên để ghi lại những bức ảnh thật đẹp du khách nhé. Hẹn gặp lại du khách tại thành phố Đà Lạt vào một ngày không xa.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>9. NHÀ THỜ DOMAINE DE MARIE</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Nhà thờ Domaine de Marie nằm trên ngọn đồi Mai Anh. Là điểm du lịch nổi tiếng về kiến trúc và cảnh quan của Đà Lạt. Từ Nhà thờ, du khách có thể phóng tầm mắt ra nhiều hướng để ngắm vẻ đẹp đầy hấp dẫn của Thành phố sương mù.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/nhatho-domaine-1.jpg" style={{width: '640px', height: '425px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Nơi đây được xây dựng theo phong cách cổ điển châu Âu thế kỷ 17. Với những bức tường xây bằng đá chẻ tới ngang bệ cửa sổ, kiểu kiến trúc vùng miền Bắc nước Pháp.</span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Nét đặc trưng của nhà thờ Domaine de Marie là hệ thống mái che nhìn tựa như mái nhà rông của đồng bào dân tộc bản địa. Một hình ảnh đặc biệt nữa của nhà thờ Domain de Marie là kiến trúc không có tháp chuông như những nhà thờ khác. Do luôn được quét vôi màu hồng đậm nên trong ráng chiều hay lúc mặt trời lên. Nhà thờ Domain de Marie trở nên nổi bật và toát nên sự uy nghiêm của một công trình tôn giáo.</span></span></p>
                          <p><strong><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>10. ĐỒI CHÈ CẦU ĐẤT</span></span></strong></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Đồi chè nằm ở thôn Xuân Trường. Là một khung cảnh thiên nhiên đẹp yên bình, nhẹ nhàng. Cảnh đẹp và khí hậu nơi đây quanh năm ôn hòa, mát mẻ. Sắc xanh của những đồi chè hòa với sắc vàng của hoa dã quỳ mỗi độ thu về. Tạo nên một bức tranh vô cùng ấn tượng. Du khách không nên bỏ lỡ cơ hội được ngắm nhìn và tận hưởng cảm giác thú vị. Đồi chè nằm cách thành phố Đà Lạt 25km nên bạn có thể dễ dàng di chuyển đến đây.</span></span></p>
                          <p style={{textAlign: 'center'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><img alt="" src="/uploads/images/diem-tham-quan/doi-tra-cau-dat-1.jpg" style={{width: '640px', height: '401px'}} /></span></span></p>
                          <p><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}>Trên đây là những chia sẻ của Cộng đồng đánh giá dịch vụ uy tín nhất Việt Nam giới thiệu đến các bạn những địa điểm du lịch đẹp và hấp dẫn nhất ở Đà Lạt. Đó đều là những điểm đến hấp dẫn, là những khung cảnh thiên nhiên tươi đẹp, độc đáo hiếm có. Mang lại cho con người một cảm giác thư thái và thật sảng khoái. Đến đây bạn sẽ có những trải nghiệm tuyệt vời và vô cùng mới mẻ. Ngoài ra còn có vô số những điều thú vị để bạn khám phá và tìm hiểu. Chúc các bạn sẽ có một chuyến đi vui vẻ và nhiều niềm vui khi đến với thành phố Đà Lạt mộng mơ.</span></span></p>
                          <p style={{textAlign: 'right'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><em><strong>Nguồn:&nbsp;top10vietnam.vn</strong></em></span></span></p>
                          <p style={{textAlign: 'right'}}><span style={{fontSize: '14px'}}><span style={{fontFamily: 'arial,helvetica,sans-serif'}}><em><strong>Ảnh: Internet</strong></em></span></span></p>
                        </div>
                        <div className="share share-out mt-30">
                          Chia sẻ: 
                          <a href="javascript:void(0)" onclick="share_facebook('http://ngoclan.ttchotels.com/vi//diem-tham-quan/top-10-dia-diem-du-lich-dep-va-hap-dan-nhat-tai-da-lat', 'http://ngoclan.ttchotels.com/uploads/images/diem-tham-quan/doiche-avatar-2.jpg')" title="Chia sẻ bài viết lên Facebook"><i className="fa fa-facebook" aria-hidden="true" /></a>
                          <a className="twitter-share-button" target="_blank" href="https://twitter.com/intent/tweet?text=TOP 10 ĐỊA ĐIỂM DU LỊCH ĐẸP VÀ HẤP... http://ngoclan.ttchotels.com/vi//diem-tham-quan/top-10-dia-diem-du-lich-dep-va-hap-dan-nhat-tai-da-lat" title="Chia sẻ bài viết lên Twitter"><i className="fa fa-twitter" aria-hidden="true" /></a>
                          <a href="https://plus.google.com/share?url=http://ngoclan.ttchotels.com/vi//diem-tham-quan/top-10-dia-diem-du-lich-dep-va-hap-dan-nhat-tai-da-lat" target="_blank" title="Chia sẻ bài viết lên Google Plus"><i className="fa fa-google-plus" aria-hidden="true" /></a>
                        </div>
                        <div className="tag mt-20">
                          Từ khóa bài viết: 
                          <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/tag/dalat" title="dalat">dalat</a>
                          , <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/tag/thung-lung-tinh-yeu" title="Thung lung tinh yeu">Thung lung tinh yeu</a>
                          , <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/tag/doi-che" title="đồi chè">đồi chè</a>
                          , <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/tag/thac-da-lat" title="thác đà lạt">thác đà lạt</a>
                        </div>
                      </div>
                      <div className="col-sm-4 clearfix">
                        <div className="col-right">
                          <div className="blog-item blog-nt favo">
                            <div className="tt-blog">Các địa điểm khác</div>
                            <ul className="list-nb">
                              <li>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/9-dia-diem-du-lich-phai-di-khi-den-da-lat"><img src="/uploads/images/hotel-ttc-hotel-premium-ngoc-lan/news/sightseeing/thung-lung-tinh-yeu(1).jpg?w=260&h=145&mode=crop&scale=both" alt="Thung Lũng Tình Yêu huyền ảo" title="Thung Lũng Tình Yêu huyền ảo" /></a>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/9-dia-diem-du-lich-phai-di-khi-den-da-lat" className="tt">9 địa điểm du lịch phải đi khi đến Đà Lạt</a>
                              </li>
                              <li>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/7-diem-den-khong-the-bo-qua-cho-tuan-trang-mat-cuoi-nam"><img src="/uploads/images/tin-tuc/nha-trang.jpg?w=260&h=145&mode=crop&scale=both" alt="Nha Trang" title="Nha Trang" /></a>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/7-diem-den-khong-the-bo-qua-cho-tuan-trang-mat-cuoi-nam" className="tt">7 ĐIỂM ĐẾN “KHÔNG THỂ BỎ QUA” CHO TUẦN TRĂNG MẬT CUỐI NĂM</a>
                              </li>
                              <li>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/rau-bac-thang-net-duyen-vung-ven-do-da-lat"><img src="/uploads//images/hotel-ttc-hotel-premium-ngoc-lan/files/gp-ruongbacthang.jpg?w=260&h=145&mode=crop&scale=both" alt="rau bac thang" title="rau bac thang" /></a>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/rau-bac-thang-net-duyen-vung-ven-do-da-lat" className="tt">Rau bậc thang - Nét duyên vùng ven đô Đà lạt</a>
                              </li>
                              <li>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/nhung-cung-duong-hoa-da-quy-o-da-lat"><img src="/uploads//images/hotel-ttc-hotel-premium-ngoc-lan/images/hoa-da-quy-2.jpg?w=260&h=145&mode=crop&scale=both" alt="hoa dã quỳ" title="hoa dã quỳ" /></a>
                                <a href="http://ngoclan.ttchotels.com/vi//diem-tham-quan/nhung-cung-duong-hoa-da-quy-o-da-lat" className="tt">Những cung đường hoa dã quỳ ở Đà Lạt</a>
                              </li>
                            </ul>
                            <a className="btn-g mt-10" href="http://ngoclan.ttchotels.com/vi//diem-tham-quan" title="Điểm tham quan">Xem thêm&nbsp;&nbsp; <i className="fa fa-angle-right" aria-hidden="true" /></a>
                          </div>
                          <div className="blog-item blog-event">
                            <div className="tt-blog">Sự kiện nổi bật</div>
                          </div>
                        </div>
                      </div>
                    </div>
        );
    }
}
export default Dalat;